parameters:
  sourceBranch: 'env/dev'  
  targetBranch: 'main'
  projectName: '<YOUR_PROJECT_NAME>'  

jobs:
  - job: 
    displayName: Create Pull requests
    pool:
      name: K8S-AZURE-AWS
    steps:
      - bash: |
          az repos pr create --description "$(Build.SourceVersionMessage) ${{ parameters.sourceBranch }} to ${{ parameters.targetBranch }}" \
                                      --source-branch ${{ parameters.sourceBranch }} \
                                      --target-branch ${{ parameters.targetBranch }} \
                                      --repository $(Build.Repository.Name) \
                                      --project "${{ parameters.projectName }}" \
                                      --title "$(Build.SourceVersionMessage) ${{ parameters.sourceBranch }} to ${{ parameters.targetBranch }}"
        displayName: Create Pull requests
        env:
          AZURE_DEVOPS_EXT_PAT: "$(System.AccessToken)"